InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/src/java/com/vur/geo/controller/PaisController.java
package com.vur.geo.controller;

import Modelo.Pais;
import com.vur.controller.util.JsfUtil;
import com.vur.controller.util.PaginationHelper;
import com.vur.geo.facade.PaisFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "paisController")
@SessionScoped
public class PaisController implements Serializable {

    private Pais current;
    private DataModel items = null;
    @EJB
    private com.vur.geo.facade.PaisFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public PaisController() {
    }

    public Pais getSelected() {
        if (current == null) {
            current = new Pais();
            selectedItemIndex = -1;
        }
        return current;
    }

    private PaisFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Pais) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Pais();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/com/vur/properties/vu").getString("PaisCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/com/vur/properties/vu").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Pais) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/com/vur/properties/vu").getString("PaisUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/com/vur/properties/vu").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Pais) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/com/vur/properties/vu").getString("PaisDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/com/vur/properties/vu").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Pais getCurrent() {
        return current;
    }

    public void setCurrent(Pais current) {
        this.current = current;
    }
    
    

    @FacesConverter(forClass = Pais.class)
    public static class PaisControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PaisController controller = (PaisController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "paisController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Pais) {
                Pais o = (Pais) object;
                return getStringKey(o.getIdpais());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Pais.class.getName());
            }
        }

    }

}

InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/web/app/ciudadano/ciudadano.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <title>#{vu.vci}</title> 
        <h:outputStylesheet library="css" name="reset.css"  />        
        <h:outputStylesheet  library="css" name="bootstrap.min.css"  />
        <h:outputStylesheet library="css" name="font-awesome.min.css"  />
        <h:outputStylesheet library="css" name="font-roboto.css"  />
        <h:outputStylesheet library="css" name="media.css"  />
        <h:outputStylesheet library="css" name="#{vu.css1}"  />
        <h:outputScript library="js" name="bootstrap.min.js"/>
        <h:outputScript library="js" name="script.js"/> 
    </h:head>
    <h:body>
        <div id="content" class="container">

            <div id="cabecera" class="row" style="text-align: center">
                <h:form>
                    <span  class="col-xs-2 hidden-xs">
                        <div   id="elTel">8000-258963</div>
                        <div><i onmouseover="mostrar()"  onmouseout="ocultar()"  class="fa fa-phone "></i>
                        </div>
                    </span>

                    <span class="col-xs-2 hidden-xs">
                        <h:commandLink value="Nueva Solicitud" action="#{solicitudBean.nuevaSolicitud()}"/>&nbsp;
                    </span>
                    <span class="col-xs-2 visible-xs">
                        <h:commandLink title="Nueva Solicitud" action="#{solicitudBean.nuevaSolicitud()}">
                            <i class="fa fa-file-o fa-1x"></i>
                        </h:commandLink>
                    </span>
                    <span class="col-xs-2 hidden-xs">
                        <h:commandLink value="Lista de Solicitudes" action="#{solicitudBean.verRequerimientosCiuidadano()}"/>&nbsp;
                    </span>
                    <span class="col-xs-2 visible-xs">
                        <h:commandLink title="Lista de Solicitudes" action="#{solicitudBean.verRequerimientosCiuidadano()}">
                            <i class="fa fa-file-text fa-1x"></i>
                        </h:commandLink>
                    </span>

                    <span class="col-xs-2 hidden-xs">
                        <h:commandLink value="Mis Datos" action="misDatos"/>
                    </span>
                    <span class="col-xs-2 visible-xs">&nbsp;
                        <h:commandLink title="Mis Datos" action="misDatos">
                            <i class="fa fa-user fa-1x"></i>
                        </h:commandLink>
                    </span>

                    <span class="col-xs-2 hidden-xs">&nbsp;
                        <h:commandLink value="Salir" action="#{loginBean.logOut()}"/>&nbsp;
                    </span>
                    <span class="col-xs-2 visible-xs">&nbsp;
                        <h:commandLink title="Salir"  action="#{loginBean.logOut()}">
                            <i class="fa fa-times-circle-o fa-1x"></i>
                        </h:commandLink>
                    </span>
                    <span class="col-xs-1" style="text-align: right">
                        &nbsp;
                    </span>
                    <span class="col-xs-1 hidden-xs" style="text-align: right">
                        <h:commandLink action="ciudadano">
                            <i class="fa #{vu.home} fa-2x  "></i>
                        </h:commandLink>
                    </span>
                    <span class="col-xs-1 visible-xs" style="text-align: right">
                        <h:commandLink action="ciudadano">
                            <i class="fa #{vu.home} "></i>
                        </h:commandLink>
                    </span>
                </h:form>
            </div>

            <div class="row cuerpo2" >
                <div id="titulo" class="col-xs-12 hidden-xs" style="color: #fff" >#{vu.vur}</div>
                 <div  id="titulo" class="col-xs-12 visible-xs" style="color: #fff; font-size: 19px" >#{vu.vur}</div>
                <div class="col-xs-2 hidden-xs ">
                    <h:graphicImage  height="100" width="120" name="#{vu.logo}" library="images"/>
                </div>
                <div class="col-xs-1 ">
                    &nbsp;
                </div>
                <div class="col-xs-7 verde ">
                    Hola: #{loginBean.users.idUsuario.nombreCompleto}<br/>
                    BIENVENIDO <br/>
                </div>
                <div class="col-xs-2 ">   &nbsp;  <br/><br/><br/><br/><br/> </div>
                <div class="col-xs-2 " >   &nbsp;   </div>
                <div class="col-xs-9 hidden-xs ">             
                    <div class="verde"><span>Novedades</span><span style="float: right;font-size: 12px;"> Hola: hace #{loginBean.ultimoIngreso()} no se conecta</span>
                        <br/>
                    </div>
                    <div class="ocreClaro"></div>
                </div>
            </div>
            <div class="row" style="margin:-5px 0 0 -23px; width: 100%">
                <div style=" width: 110%" id="pie" class="col-xs-12 visible-xs">&nbsp;<br/>&nbsp;<br/></div>
                <div style=" width: 105%" id="pie" class="col-xs-12 hidden-xs">&nbsp;<br/>&nbsp;<br/></div>
          
            </div>
        </div>
    </h:body>
</html>

InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/web/app/ciudadano/form.jsp
<%-- 
    Document   : form
    Created on : 08/03/2011, 05:17:13 PM
    Author     : dsilva
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Cargar archivo</title>
        <style type="text/css">
            body {
                background-color:#eff5fa;
                padding: 10px 20px 10px 25px;
                font-family: arial;
                color: #4e6a71;
            }
            .button{
                padding: 10px 26px 10px 26px;
                color: #fff;
                background-color: #018706;
                border: 0px;
                border-radius: 0px 0px;
                -webkit-border-radius: 0px 0px;  /* Safari  */
                -moz-border-radius: 0px 0px;
            }
            .button:hover{
                box-shadow: 2px 2px 2px #003602;
            }
            input{
                border: 0px;
                border-radius: 0px 0px;
            }
        </style>
    </head>
    <body>
        <h1>Cargar archivo</h1>
        <form action="<c:url value='/servlet/upload'/>" method="POST" enctype="multipart/form-data">
            Archivo:&nbsp;&nbsp;
            <input  type="file" name="archivo" value="" /><br/><br/>
            <button id="cargar" class="button" type="submit">Cargar</button>
        </form>
    </body>
</html>

InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/web/app/ciudadano/inicio.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
      <h:head>
        <title>admin</title>
        <script type="text/javascript">
            function redireccionar() {
                window.location = "../../inicio.xhtml";
            }
            setTimeout('redireccionar()', 500);
        </script>
    </h:head>
    <h:body>         
        un momento por favor
    </h:body>
</html>

InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/web/app/ciudadano/nuevoRequerimiento.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ezcomp="http://java.sun.com/jsf/composite/ezcomp">
    <h:head>
        <title>Nuevo Requerimiento</title>
        <h:outputStylesheet library="css" name="reset.css"  />        
        <h:outputStylesheet  library="css" name="bootstrap.min.css"  />
        <h:outputStylesheet library="css" name="font-awesome.min.css"  />
        <h:outputStylesheet library="css" name="font-roboto.css"  />
        <h:outputStylesheet library="css" name="media.css"  />
        <!--h:outputStylesheet  library="css" name="text.css"  /-->
        <h:outputStylesheet library="css" name="#{vu.css1}"  />
        <h:outputScript library="js" name="bootstrap.min.js"/>
        <h:outputScript library="js" name="script.js"/> 
    </h:head>
    <h:body>
        <div id="content" class="container">            
            <div id="cabecera" class="row" >
                <h:form>
                    <span  class="col-xs-2 hidden-xs">
                        <div   id="elTel">&nbsp;&nbsp; 8000-258963&nbsp;&nbsp;</div>
                        <div><i onmouseover="mostrar()"  onmouseout="ocultar()"  class="fa fa-phone fa-2x"></i>
                        </div>
                    </span>

                    <span class="col-xs-2 hidden-xs">&nbsp;&nbsp;
                        <h:commandLink value="Nueva Solicitud" action="#{solicitudBean.nuevaSolicitud()}"/>&nbsp;
                    </span>
                    <span class="col-xs-2 visible-xs">&nbsp;&nbsp;
                        <h:commandLink title="Nueva Solicitud" action="#{solicitudBean.nuevaSolicitud()}">
                            <i class="fa fa-file-o fa-1x"></i>
                        </h:commandLink>
                    </span>
                    <span class="col-xs-2 hidden-xs">&nbsp;
                        <h:commandLink value="Lista de Solicitudes" action="#{solicitudBean.verRequerimientosCiuidadano()}"/>&nbsp;
                    </span>
                    <span class="col-xs-2 visible-xs">&nbsp;
                        <h:commandLink title="Lista de Solicitudes" action="#{solicitudBean.verRequerimientosCiuidadano()}">
                            <i class="fa fa-file-text fa-1x"></i>
                        </h:commandLink>
                    </span>

                    <span class="col-xs-2 hidden-xs">&nbsp;
                        <h:commandLink value="Mis Datos" action="misDatos"/>
                    </span>
                    <span class="col-xs-2 visible-xs">&nbsp;
                        <h:commandLink title="Mis Datos" action="misDatos">
                            <i class="fa fa-user fa-1x"></i>
                        </h:commandLink>
                    </span>

                    <span class="col-xs-2 hidden-xs">&nbsp;
                        <h:commandLink value="Salir" action="#{loginBean.logOut()}"/>&nbsp;
                    </span>
                    <span class="col-xs-2 visible-xs">&nbsp;
                        <h:commandLink title="Salir"  action="#{loginBean.logOut()}">
                            <i class="fa fa-times-circle-o fa-1x"></i>
                        </h:commandLink>
                    </span>
                    <span class="col-xs-1" style="text-align: right">
                        &nbsp;
                    </span>
                    <span class="col-xs-1 hidden-xs" style="text-align: right">
                        <h:commandLink action="ciudadano">
                            <i class="fa #{vu.home} fa-2x  "></i>
                        </h:commandLink>
                    </span>
                    <span class="col-xs-1 visible-xs" style="text-align: right">
                        <h:commandLink action="ciudadano">
                            <i class="fa #{vu.home} "></i>
                        </h:commandLink>
                    </span>
                </h:form>
            </div>

            <div id="cuerpo">
                <div class="headContent row">
                    <div id="titulo" class="col-xs-9 hidden-xs" style="color: #3F4036" >
                        ${vu.vur}<br/>
                    </div>
                    <div  id="titulo" class="col-xs-12 visible-xs" style="color: #3F4036; font-size: 18px" >
                        ${vu.vur}<br/>
                    </div>
                    <div style="float: right" class="col-xs-3 hidden-xs">
                        <h:graphicImage  height="100" width="120" name="${vu.logo}" library="images"/>
                    </div>  
                    <div style="margin-left: 55px" class="verde col-xs-8 col-lg-5 col-sm-5 col-md-5">
                        Hola: #{loginBean.users.idUsuario.nombreCompleto}<br/>
                        BIENVENIDO <br/>
                    </div>

                    <div class="col-xs-5 ">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class=" col-xs-1">
                        &nbsp;
                    </div>
                    <div class="marco col-xs-8">
                        <h3>Nuevo Requerimiento Ciudadano</h3>
                        <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                        <h:form id="form">
                            <h:panelGrid columns="2">
                                <h:outputLabel value="IdSolicitud:" for="idSolicitud" />
                                <h:inputText disabled="true" id="idSolicitud" value="#{solicitudBean.solicitud.idSolicitud}" title="IdSolicitud" required="true" requiredMessage="The IdSolicitud field is required."/>
                                <h:outputLabel value="Asunto:" for="concepto" />
                                <h:inputText size="65"  id="concepto" value="#{solicitudBean.solicitud.concepto}" title="Concepto" />
                                <h:outputLabel value="Descripcion:" for="descripcion" />
                                <h:inputTextarea    rows="4" cols="30" id="descripcion" value="#{solicitudBean.solicitud.descripcion}" title="Descripcion" />
                                <h:outputLabel value="Dependencia: " for="idDependencia" />
                                <h:selectOneMenu id="idDependencia" value="#{solicitudBean.dependencia}" title="Dependencia" >
                                    <f:selectItems value="#{dependenciaController.itemsAvailableSelectOne}"/>
                                    <f:ajax render="idEjeTematico" execute="@form" onevent="showDateIndicator" />
                                </h:selectOneMenu>
                                <h:outputLabel value="Tema: " for="idEjeTematico" />
                                <h:selectOneMenu id="idEjeTematico" value="#{solicitudBean.solicitud.idEjeTematico}" title="IdEjeTematico" >
                                    <f:selectItems value="#{solicitudBean.itemsEjeTematicoDedependencia}"/>
                                </h:selectOneMenu>
                                <h:outputLabel value="Tipo Requerimiento:" for="idTipoRequerimiento" />
                                <h:selectOneMenu id="idTipoRequerimiento" value="#{solicitudBean.solicitud.idTipoRequerimiento}" title="IdTipoRequerimiento" >
                                    <f:selectItems value="#{tipoRequerimientoController.itemsAvailableSelectOne}"/>
                                </h:selectOneMenu>
                            </h:panelGrid>

                            <ezcomp:ajaxGif/>
                            <!-- Sigue  binding="{subirArchivosBean.adjuntosDataTable}" -->
                            <div style="padding: 20px" id="marcoDiv">  

                                <h:panelGrid columns="1"  bgcolor="#ebf1f6" >
                                    <h:outputText value="Haga click en agregar para anexar un  Archivo"/>
                                    <h:panelGroup id="grp">                                        
                                        <h:dataTable id="adjuntos" value="#{subirArchivosBean.entradaActual.adjuntos}"   var="a" >
                                            <h:column>
                                                <i class="fa fa-paperclip fa-2x"></i>
                                            </h:column>
                                            <h:column>
                                                &nbsp; &nbsp;
                                            </h:column>
                                            <h:column>
                                                <h:outputText  value="#{a.nombreAdjunto}" />
                                            </h:column>
                                        </h:dataTable>
                                        <h:button  class="button2" title="Agregar Archivo" image="../../images/fa-upload-1.png"   onclick='window.open("#{facesContext.externalContext.requestContextPath}/servlet/uploadCiu/form", "archivo Excel", "width=500,height=200")'/>
                                        &nbsp;  &nbsp; &nbsp; &nbsp;
                                        <br/><br/>
                                    </h:panelGroup>
                                    <h:commandButton class="button" value="Enviar Requerimiento" action="#{solicitudBean.actualizarCrearSolicitud('listaRequerimientos')}" />

                                    <h:commandButton style="visibility:hidden" value="Recargar..." id="recargar" class="button">
                                        <f:ajax render="grp" execute="@form" onevent="showDateIndicator"/>
                                    </h:commandButton>
                                    <h:commandLink class="button" value="Limpiar Formulario" action="#{solicitudBean.visualizarNuevaSolicitud()}"></h:commandLink>
                                </h:panelGrid>

                            </div>
                        </h:form>
                        <!--fin subir archivo-->
                    </div>
                    <div class=" col-xs-1">
                        &nbsp;
                    </div>
                </div>
                <div class="row" style="margin:-5px 0 0 -23px; width: 100%">
                    <div style=" width: 110%" id="pie" class="col-xs-12 visible-xs">&nbsp;<br/>&nbsp;<br/></div>
                    <div style=" width: 105%" id="pie" class="col-xs-12 hidden-xs">&nbsp;<br/>&nbsp;<br/></div>

                </div>
            </div>
        </div>

    </h:body>
</html>

InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/web/app/ciudadano/znuevoRequerimiento__.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"          
      xmlns:ezcomp="http://java.sun.com/jsf/composite/ezcomp">
    <h:head>
        <title>Nuevo Requerimiento</title>
        <ezcomp:estilos/>
         <h:outputStylesheet library="css" name="media.css"  />
    </h:head>
    <h:body>
        <div id="content" class="grid-container">
            <ezcomp:navCiudadano/>
            <div id="cuerpo" class="grid-99">
                <ezcomp:headContent/>
                <div class="marco">
                    <h2>Nuevo Requerimiento Ciudadano</h2>
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                    <h:form id="form">
                        <h:panelGrid columns="2">
                            <h:outputLabel value="IdSolicitud:" for="idSolicitud" />
                            <h:inputText disabled="true" id="idSolicitud" value="#{solicitudBean.solicitud.idSolicitud}" title="IdSolicitud" required="true" requiredMessage="The IdSolicitud field is required."/>
                            <h:outputLabel value="Asunto:" for="concepto" />
                            <h:inputText size="65"  id="concepto" value="#{solicitudBean.solicitud.concepto}" title="Concepto" />
                            <h:outputLabel value="Descripcion:" for="descripcion" />
                            <h:inputTextarea    rows="4" cols="30" id="descripcion" value="#{solicitudBean.solicitud.descripcion}" title="Descripcion" />
                            <h:outputLabel value="Dependencia: " for="idDependencia" />
                            <h:selectOneMenu id="idDependencia" value="#{solicitudBean.dependencia}" title="Dependencia" >
                                <f:selectItems value="#{dependenciaController.itemsAvailableSelectOne}"/>
                                <f:ajax render="idEjeTematico" execute="@form" onevent="showDateIndicator" />
                            </h:selectOneMenu>
                            <h:outputLabel value="Tema: " for="idEjeTematico" />
                            <h:selectOneMenu id="idEjeTematico" value="#{solicitudBean.solicitud.idEjeTematico}" title="IdEjeTematico" >
                                <f:selectItems value="#{solicitudBean.itemsEjeTematicoDedependencia}"/>
                            </h:selectOneMenu>
                            <h:outputLabel value="Tipo Requerimiento:" for="idTipoRequerimiento" />
                            <h:selectOneMenu id="idTipoRequerimiento" value="#{solicitudBean.solicitud.idTipoRequerimiento}" title="IdTipoRequerimiento" >
                                <f:selectItems value="#{tipoRequerimientoController.itemsAvailableSelectOne}"/>
                            </h:selectOneMenu>
                        </h:panelGrid>

                        <ezcomp:ajaxGif/>
                      <!-- Sigue  binding="{subirArchivosBean.adjuntosDataTable}" -->
                            <div style="padding: 20px" id="marcoDiv">  

                                <h:panelGrid columns="1"  bgcolor="#ebf1f6" >
                                    <h:outputText value="Haga click en agregar para anexar un  Archivo"/>
                                    <h:panelGroup id="grp">                                        
                                        <h:dataTable id="adjuntos" value="#{subirArchivosBean.entradaActual.adjuntos}"   var="a" >
                                            <h:column>
                                                <i class="fa fa-paperclip fa-2x"></i>
                                            </h:column>
                                            <h:column>
                                                &nbsp; &nbsp;
                                            </h:column>
                                            <h:column>
                                                <h:outputText  value="#{a.nombreAdjunto}" />
                                            </h:column>
                                        </h:dataTable>
                                        <h:button  class="button2" title="Agregar Archivo" image="../../images/fa-upload-1.png"   onclick='window.open("#{facesContext.externalContext.requestContextPath}/servlet/uploadCiu/form", "archivo Excel", "width=500,height=200")'/>
                                        &nbsp;  &nbsp; &nbsp; &nbsp;
                                        <br/><br/>
                                    </h:panelGroup>
                                    <h:commandButton class="button" value="Enviar Requerimiento" action="#{solicitudBean.actualizarCrearSolicitud('listaRequerimientos')}" />

                                    <h:commandButton style="visibility:hidden" value="Recargar..." id="recargar" class="button">
                                        <f:ajax render="grp" execute="@form" onevent="showDateIndicator"/>
                                    </h:commandButton>
                                    <h:commandLink class="button" value="Limpiar Formulario" action="#{solicitudBean.visualizarNuevaSolicitud()}"></h:commandLink>
                                </h:panelGrid>

                            </div>
                    </h:form>
                    <!--fin subir archivo-->
                </div>
            </div>
            <div id="pie" class="grid-99">&nbsp;<br/>&nbsp;<br/></div>
        </div>
        <ezcomp:ajaxScript/>

    </h:body>
</html>