InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/src/java/com/vur/ventanillaUnica/bean/SolicitudBean.java
package com.vur.ventanillaUnica.bean;

import com.vur.controller.util.JsfUtil;
import com.vur.institucional.controller.EmpleadoController;
import Modelo.Dependencia;
import Modelo.Empleado;
import com.vur.mail.GestorJavaMail;
import com.vur.usuario.bean.LoginBean;
import com.vur.usuario.bean.GestionUsuarioBean;
import com.vur.usuario.controller.UsuarioController;
import Modelo.Users;
import Modelo.Usuario;
import com.vur.util.VurUtil;
import Modelo.Archivo;
import Modelo.Asignado;
import Modelo.Estadorequerimiento;
import Modelo.Solicitud;
import com.vur.ventanillaUnica.facade.AsignadoFacade;
import com.vur.ventanillaUnica.facade.SolicitudFacade;
import Modelo.Respuesta;
import Modelo.Rol;
import Modelo.Tiposolicitud;
import com.vur.ventanillaUnica.facade.ArchivoFacade;
import com.vur.ventanillaUnica.facade.EjeTematicoFacade;
import com.vur.ventanillaUnica.facade.EstadoRequerimientoFacade;
import com.vur.ventanillaUnica.facade.TipoSolicitudFacade;
import com.vur.ventanillaUnica.faq.facade.RespuestaFacade;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.model.SelectItem;

/**
 *
 * tiempo Humano 1 hora 3600 segundos 1 dia	86400 segundos 1 semana	604800
 * segundos 1 mes (30.44 days) 2629743 seconds 1 año (365.24 days) 31556926
 * seconds
 *
 * @since 25-06-2015
 * @version 0.0.1
 * @author jesusmarin
 */
@ManagedBean(name = "solicitudBean")
@SessionScoped
public class SolicitudBean implements Serializable {

    private Usuario usuario;
    private Solicitud solicitud;
    private Asignado asignado;
    private Respuesta respuesta;
    private Dependencia dependencia;
    private int elDiv = 589;//2  formulario de usuario nuevo/ 1 formulario de nuevo requerimiento/3 ver la solicitud creada
    private long docid;
    private String idRadicado;
    private String mes;
    private String fechaReferencia;
    private Estadorequerimiento estado;

    @EJB
    private SolicitudFacade solicitudEjb;

    @EJB
    private ArchivoFacade archivoEjb;
    @EJB
    private AsignadoFacade asignadoEjb;
    @EJB
    private TipoSolicitudFacade TipoSolicitudEjb;
    @EJB
    private EstadoRequerimientoFacade estadoRequerimientoEjb;
    @EJB
    private RespuestaFacade respuestaEjb;
    @EJB
    private EjeTematicoFacade ejeTematicoEjb;
    @ManagedProperty(value = "#{loginBean}")
    private LoginBean loginBean;
    @ManagedProperty(value = "#{usuarioController}")
    private UsuarioController usuarioController;
    @ManagedProperty(value = "#{gestionUsuarioBean}")
    private GestionUsuarioBean gestionUsuarioBean;
    @ManagedProperty(value = "#{subirArchivosBean}")
    private SubirArchivosBean subirArchivosBean;
    @ManagedProperty(value = "#{empleadoController}")
    private EmpleadoController empleadoController;

    public SolicitudBean() {
    }

    public String verRequerimientosCiuidadano() {
        elDiv = 0;
        return "listaRequerimientos";
    }

    public String verSolicitud(Solicitud item) {
        solicitud = item;
        respuesta = verRespuestaDeSolicitud(solicitud);
        elDiv = 1;
        return "listaRequerimientos";
    }

    public String verSolicitudEnBuscar(Solicitud item) {
        elDiv = 1;
        solicitud = item;
        try {
            respuesta = verRespuestaDeSolicitud(solicitud);
            JsfUtil.addSuccessMessage(" respuesta: " + respuesta.getRespuesta());
        } catch (Exception e) {
            JsfUtil.addSuccessMessage("La solicitud  aun no tiene respuesta");
        }
        return "buscarSolicitud";
    }

    /*
     @return String
     */
    public String ingresarNuevoCiudadano() {
        Rol r = new Rol();
        r.setRol("CIUDADANO");
        elDiv = 2;
        //iniciar datos de nuevo usuario
        getGestionUsuarioBean().establecerComoCiudadano();
        getGestionUsuarioBean().getCurrentUsuario().setDocid(docid);
        getGestionUsuarioBean().getCurrentUsers().setPassword(docid);
        //getGestionUsuarioBean().getCurrentUsuario().setGrupo("CIUDADANO");
        getGestionUsuarioBean().getCurrentUsers().setNumaccesos(0);
        getGestionUsuarioBean().getCurrentUsers().setMail("a@mail.com");
        getGestionUsuarioBean().getCurrentUsers().setRol(r);
        getGestionUsuarioBean().getCurrentDireccion().setWeb("www.mipagina.com");
        usuario = getGestionUsuarioBean().getCurrentUsuario();
        JsfUtil.addSuccessMessage("Ingresar datos del nuevo ciudadano al sistema :)");
        return "nuevoRequerimiento";
    }

    public String buscarSolicitudDesdeFuncionario() {
        elDiv = 0;
        List<Solicitud> l = getSolicitudesBusqueda();
        return "buscarSolicitud";
    }

    /*
     @return String
     */
    public String verSolicitudesEnFuncionario() {
        // empleado = u.getIdEmpleado();  
        elDiv = 0;// muesta la lsita de solicitud del funcionario 
        Usuario u = getLoginBean().getUsuario();
        List<Solicitud> listaSolicitudes = getSolicitudesFuncionario();
        //JsfUtil.addSuccessMessage("Solcitudes asignadas a :" + u.getNombreCompleto());
        return "verSolicitudes";
    }

    /*PAra administrador
     @return String
     */
    public String verSolicitudesFuncionarioEnAdmin() {
        // empleado = u.getIdEmpleado();  
        elDiv = 2;// muesta la lsita de solicitud del funcionario 
        Usuario u = getLoginBean().getUsuario();
        try {
            List<Solicitud> listaSolicitudes = getSolicitudesFuncionario();
        } catch (Exception e) {
            //
        }

        JsfUtil.addSuccessMessage("elDiv :" + 2);
        return "gestionRequerimientos";
    }

    public String verSolicitudesFuncionarioMobil() {
        verSolicitudesFuncionarioEnAdmin();
        return "mb_responder";
    }

    /*
     @return String
     */
    public String verSolicitudesDependencia() {
        Rol rol = getLoginBean().getUsers().getRol();
        elDiv = 3;
        //elDiv = 0;
        if (rol.equals("SUPER")) {
            Empleado e = getLoginBean().getEmpleado();
            try {
                System.out.println(" es un super " + dependencia.toString());
            } catch (Exception ex) {
            }

        } else {
            List<Solicitud> l = getSolicitudesDependencia();
        }
        JsfUtil.addSuccessMessage("elDiv :" + elDiv);
        return "requerimientosDependencia";
    }

    public String verSolicitudesDependenciaEnSuper() {
        elDiv = 3;
        List<Solicitud> l = getSolicitudesDependenciaEnSuper();
        return "requerimientosDependencia";
    }

    /*
     @return String
     */
    public String verMisSolicitudesEnDependencia() {
//        elDiv = 0;
        elDiv = 6;
        List<Solicitud> l = getSolicitudesCiudadano();
        JsfUtil.addSuccessMessage("elDiv :" + elDiv);
        return "gestionRequerimientos";
    }

    /*
     @return String
     */
    public List<Solicitud> getSolicitudesDependenciaEnSuper() {
        try {
            //System.out.println("getSolicitudesDependenciaEnSuper " + dependencia.toString());
            return consultarSolicitudesDependencia(dependencia);
        } catch (Exception e) {
            System.out.println("getSolicitudesDependenciaEnSuper Dependencia catch");
        }
        return null;
    }

    /*
     @return String
     */
    public List<Solicitud> getSolicitudesDependencia() {
        Dependencia d = new Dependencia();

        d = getLoginBean().getEmpleado().getIdCargo().getIdDependencia();
        try {
            return consultarSolicitudesDependencia(d);
        } catch (Exception e) {
            JsfUtil.addSuccessMessage("Dependencia catch");
        }
        return null;
    }

    public List<Solicitud> getListaDependencia() {
        Dependencia d = new Dependencia();
        try {
            d = getLoginBean().getUsuario().getIdEmpleado().getIdCargo().getIdDependencia();
            return consultarSolicitudesDependencia(d);
        } catch (Exception e) {
        }
        return null;
    }

    /*
     @param Dependencia
     @return List
     */
    public List<Solicitud> consultarSolicitudesDependencia(Dependencia d) {
        try {
            return getSolicitudEjb().getSolicitudesDeDependencia(d);
        } catch (Exception e) {
        }
        return null;
    }

    /*
     @return List
     */
    public List<Solicitud> getSolicitudesFuncionario() {
        try {
            Usuario u = getLoginBean().getUsuario();
            return getSolicitudEjb().getlistaAsignadasFuncionario(u, "Asignado");//listaSolicitudes;
        } catch (Exception ex) {
            JsfUtil.addSuccessMessage("Ninguna solicitud Asignada a la fecha");
            return null;
        }
    }

    /*
     @return List
     */
    public List<Solicitud> getAllSolicitudesMesSegunEstado() {
        VurUtil v = new VurUtil();
        try {
            int mint = v.verIntMes(mes);
            long iml = v.getFechaInicioMes(mint);
            long fml = v.getFechaFinMes(mint);
            Usuario u = getLoginBean().getUsuario();
            return getSolicitudEjb().getListaSolicitudSegunEstado(estado, iml, fml, fechaReferencia);//listaSolicitudes;
        } catch (Exception ex) {
            JsfUtil.addSuccessMessage("Ninguna solicitud Asignada a la fecha");
            return null;
        }
    }

    /*
     @return List
     */
    public int getCountSolicitudesMesSegunEstado() {
        VurUtil v = new VurUtil();
        try {
            int mint = v.verIntMes(mes);
            long iml = v.getFechaInicioMes(mint);
            long fml = v.getFechaFinMes(mint);
            Usuario u = getLoginBean().getUsuario();
            return getSolicitudEjb().countSolicitudesSegunEstadoEnFechas(estado, iml, fml, fechaReferencia);// etListaSolicitudSegunEstado(estado, iml, fml);//listaSolicitudes;

InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/web/app/admin/admin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ezcomp="http://java.sun.com/jsf/composite/ezcomp">
    <h:head>
        <title>#{vu.vci} Admin</title>   
        <ezcomp:estilos/>
    </h:head>
    <h:body>
        <div id="content" class="grid-container">
            <ezcomp:navAdmin/>

            <div class="cuerpo2">
                <div id="titulo" class="grid-100" style="color: #fff" >#{vu.vur}</div>

                <div class="grid-20   ">
                    <h:graphicImage  height="100" width="120" name="#{vu.logo}" library="images"/>
                </div>
                <div class="grid-5  ">
                    &nbsp;
                </div>
                <div class="grid-30 verde ">
                    Hola: #{loginBean.users.idUsuario.nombreCompleto}<br/>
                    BIENVENIDO <br/>
                </div>
                <div class="grid-35  ">   &nbsp;  <br/><br/><br/><br/><br/> </div>
                <div class="grid-15   " >   &nbsp;   </div>
                <div class="grid-55  ">             
                    <div class="verde"><span>Novedades</span><span style="float: right;font-size: 12px;"> Hola: hace #{loginBean.ultimoIngreso()} no se conecta</span>
                        <br/>

                    </div>
                    <ezcomp:countSolicitudEmp/>
                </div>
                <div class="clear"/>
            </div>
            <div id="pie" class="grid-99">&nbsp;<br/>&nbsp;<br/></div>
        </div>

    </h:body>
</html>

InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/web/app/admin/form.jsp
<%-- 
    Document   : form
    Created on : 08/03/2011, 05:17:13 PM
    Author     : dsilva
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Cargar archivo</title>
        <style type="text/css">
            body {
                background-color:#eff5fa;
                padding: 10px 20px 10px 25px;
                font-family: arial;
                color: #4e6a71;
            }
            .button{
                padding: 10px 26px 10px 26px;
                color: #fff;
                background-color: #018706;
                border: 0px;
                border-radius: 0px 0px;
                -webkit-border-radius: 0px 0px;  /* Safari  */
                -moz-border-radius: 0px 0px;
            }
            .button:hover{
                box-shadow: 2px 2px 2px #003602;
            }
            input{
                border: 0px;
                border-radius: 0px 0px;
            }
        </style>
    </head>
    <body>
        <h1>Cargar archivo</h1>
        <form action="<c:url value='/servlet/upload'/>" method="POST" enctype="multipart/form-data">
            Archivo:&nbsp;&nbsp;
            <input  type="file" name="archivo" value="" /><br/><br/>
            <button class="button" type="submit">Cargar</button>
        </form>
    </body>
</html>

InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/web/app/admin/inicio.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>admin</title>
        <h:outputStylesheet library="css" name="jsfcrud.css"  />
        <script type="text/javascript">
            function redireccionar() {
                window.location = "../../inicio.xhtml";
            }
            setTimeout('redireccionar()', 500);
        </script>
    </h:head>
    <h:body>       
        <span style="color:#CECFCA ">
            un momento por favor
        </span>
    </h:body>
</html>

InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/web/app/admin/mb_responder.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ezcomp="http://java.sun.com/jsf/composite/ezcomp">
    <h:head>
        <title>#{vu.vci}</title>
        <h:outputStylesheet library="css" name="reset.css"  />        
        <h:outputStylesheet  library="css" name="bootstrap.min.css"  />
        <h:outputStylesheet library="css" name="font-awesome.min.css"  />
        <h:outputStylesheet library="css" name="font-roboto.css"  />
        <h:outputStylesheet library="css" name="media.css"  />
        <h:outputStylesheet library="css" name="#{vu.css1}"  />
        <h:outputScript library="js" name="bootstrap.min.js"/>
        <h:outputScript library="js" name="script.js"/> 
    </h:head>
    <h:body>
        <ezcomp:mb_responder/>
    </h:body>
</html>

InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/web/app/admin/misDatos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ezcomp="http://java.sun.com/jsf/composite/ezcomp">
    <h:head>
        <title>Mis Datos #{vu.vci} Admin</title>
        <ezcomp:estilos/>
        <h:outputStylesheet library="css" name="estilo.css"  />
    </h:head>
    <h:body>
        <div id="content" class="grid-container">
            <ezcomp:navAdmin/>
            <div id="cuerpo" class="grid-99 cuerpo">
                <ezcomp:headContent/>
                <h:form>
                    <ezcomp:misDatos/>
                </h:form>
                <div class="clear"/>
            </div>
            <div id="pie" class="grid-99">&nbsp;<br/>&nbsp;<br/></div>
            <div class="clear"/>
        </div>
    </h:body>
</html>

InfoDocs-master-65f2f2a4e3c87f20546341ee3cf8583aa4bbaf2a/web/app/admin/requerimientosDependencia.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ezcomp="http://java.sun.com/jsf/composite/ezcomp"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>#{vu.vci} Admin</title>
        <ezcomp:estilos/>
        <h:outputStylesheet library="css" name="estilo.css"  />
    </h:head>
    <h:body>
        <!-- ve las solicitudes asignadas a la dependencia-->
        <!-- asignacion de  solicitud a funcionario-->
        <!-- ver Datos de solicitud a (Respuesta y Anexos)-->
        <!-- el div =3 visualiza lista de solicitudes de dependencia-->
        <!-- el div =7 visualiza la solicitud seleccionada-->
        <!-- el div =2 visualiza la asignacion de solicitud seleccionada-->
        <div id="content" class="grid-container">
            <ezcomp:navAdmin/>
            <div class="cuerpo">
                <ezcomp:navSolicitudAdmin/>
                <ezcomp:headContent/>
                <div class=" grid-5">&nbsp;</div>

                <div class="marco grid-90">

                    <div class="panel ">
                        <!-- el div =3 visualiza respuesta actual de funcionario-->
                        <h:form id="form3" styleClass="jsfcrud_list_form" rendered="#{solicitudBean.elDiv == 3}">                               
                            <h1>Dependencia: #{solicitudBean.dependencia}</h1>
                            <h:panelGrid columns="2" >
                                <h:dataTable rendered="#{solicitudBean.solicitudesDependencia.size()>0}"  rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" 
                                             border="0" cellpadding="2" cellspacing="0" 
                                             style="border:solid 1px"
                                             value="#{solicitudBean.solicitudesDependencia}" var="item">
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value="Id"/>
                                        </f:facet>
                                        <h:outputText value="#{item.idSolicitud}"/>
                                    </h:column>                                
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value="Concepto"/>
                                        </f:facet>
                                        <h:outputText value="#{item.concepto}"/>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value="Creado"/>
                                        </f:facet>
                                        <h:outputText value="#{solicitudBean.getFecha(item.creado)}">
                                            <f:convertDateTime pattern="dd/MM/yyyy" />
                                        </h:outputText>
                                    </h:column>                                
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value="&nbsp;"/>
                                        </f:facet>
                                        <h:outputText value="&nbsp;&nbsp;&nbsp;&nbsp;"/>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value="Vence"/>
                                        </f:facet>
                                        <h:outputText value="#{solicitudBean.getFecha(item.vence)}">
                                            <f:convertDateTime pattern="dd/MM/yyyy" />
                                        </h:outputText>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value="&nbsp;"/>
                                        </f:facet>
                                        <h:outputText value="&nbsp;&nbsp;&nbsp;&nbsp;"/>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value="Tema"/>
                                        </f:facet>
                                        <h:outputText value="#{item.idEjeTematico.tema}"/>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value="Usuario"/>
                                        </f:facet>
                                        <h:outputText value="#{item.idUsuario.nombreCompleto}"/>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value="Estado"/>
                                        </f:facet>
                                        <h:outputText value="#{solicitudBean.verEstadoDeSolicitud(item)}"/>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value="Tipo"/>
                                        </f:facet>
                                        <h:outputText value="#{item.idTipoSolicutd.tipo}"/>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value="Requerimiento"/>
                                        </f:facet>
                                        <h:outputText value="#{item.idTipoRequerimiento.tipo}"/>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">
                                            <h:outputText value="Asignado"/>
                                        </f:facet>
                                        <h:outputText value="#{solicitudBean.verEmpleadoAsignado(item)}"/>
                                    </h:column>
                                    <h:column>
                                        <f:facet name="header">
                                            <i class='fa fa-eye'></i> &nbsp;&nbsp;&nbsp;&nbsp;
                                        </f:facet>                                
                                        <h:commandLink action="#{solicitudBean.visualizarSolicitudEnDependencia(item)}"> 
                                            &nbsp; &nbsp;<h:graphicImage height="13" width="20" library="images" name="eyes.png"/>
                                        </h:commandLink>
                                    </h:column>
                                </h:dataTable>
                            </h:panelGrid>
                        </h:form>

                        <!---elDiv = 7 Visualiza la solicitud seleccionada para ser asgnada .toString()-->
                        <h:form rendered="#{solicitudBean.elDiv==7}" styleClass="jsfcrud_list_form">
                            <h:panelGrid columns="2">
                                <h:outputText value="Id:"/>
                                <h:outputText value="#{solicitudBean.solicitud.idSolicitud}" title="IdSolicitud"/>
                                <h:outputText value="Asunto:"/>
                                <h:outputText value="#{solicitudBean.solicitud.concepto}" title="Concepto"/>
                                <h:outputText value="Detalle:"/>
                                <h:outputText value="#{solicitudBean.solicitud.descripcion}" title="Descripcion"/>
                                <h:outputText value="Creado:"/>
                                <h:outputText value="#{solicitudBean.getFechaCreado(solicitudBean.solicitud)}" title="Creado">
                                    <f:convertDateTime pattern="dd/MM/yyy HH:MM:SS"/>
                                </h:outputText>
                                <h:outputText value="Vence:"/>
                                <h:outputText value="#{solicitudBean.getFechaVence(solicitudBean.solicitud)}" title="Vence">
                                    <f:convertDateTime pattern="dd/MM/yyy HH:MM:SS"/>
                                </h:outputText>
                                <h:outputText value="Tema:"/>
                                <h:outputText value="#{solicitudBean.solicitud.idEjeTematico.tema}" title="IdEjeTematico"/>
                                <h:outputText value="Ciudadano:"/>
                                <h:outputText value="#{solicitudBean.solicitud.idUsuario.nombreCompleto}" title="IdUsuario"/>
                                <h:outputText value="Estado:"/>
                                <h:outputText value="#{solicitudBean.solicitud.idEstadoRequerimiento.estado}" title="Estado Requerimiento"/>
                                <h:outputText value="Tipo:"/>
                                <h:outputText value="#{solicitudBean.solicitud.idTipoSolicutd.tipo}" title="Tipo Solicutd"/>
                                <h:outputText value="Requerimiento&nbsp;&nbsp;&nbsp;&nbsp;:"/>
                                <h:outputText value="#{solicitudBean.solicitud.idTipoRequerimiento.tipo}" title="Tipo Requerimiento"/>
                            </h:panelGrid>
                            <h:commandLink class="button" value="Asignar" action="#{solicitudBean.asignarSolicitud()}">                                
                            </h:commandLink>
                        </h:form>
                        <!---elDiv = 2 Visualiza la asignacion de  solicitud seleccionada para ser asgnada -->
                        <h:form  styleClass="jsfcrud_list_form" rendered="#{solicitudBean.elDiv==2}">

                            Solicitud : #{solicitudBean.solicitud.toString()}<br/>

                            <h:panelGrid columns="2">
                                <h:outputText value="IdAsignado:"/>
                                <h:outputText value="#{solicitudBean.asignado.idAsignado}" title="IdAsignado"/>
                                <h:outputText value="FechaAsignado:"/>
                                <h:outputText value="#{solicitudBean.asignado.fechaAsignado}" title="FechaAsignado">
                                    <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                                </h:outputText>
                                <h:outputText value="Habilitado:"/>
                                <h:outputText value="#{solicitudBean.asignado.habilitado}" title="Habilitado"/>
                                <h:outputText value="Estado:"/>
                                <h:outputText value="#{solicitudBean.asignado.estado}" title="Estado"/>
                                <h:outputText value="IdSolicitud:"/>
                                <h:outputText value="#{solicitudBean.asignado.idSolicitud}" title="IdSolicitud"/>
                                <h:outputText value="Empleado:"/>
                                <h:selectOneMenu value="#{solicitudBean.asignado.idEmpleado}" title="IdEmpleado">
                                    <f:selectItems value="#{empleadoController.itemsEmpleadosPorDependenciaSelectOne}"/>
                                    <f:ajax render="empl" execute="@form" onevent="showDateIndicator"/>
                                </h:selectOneMenu>
                                <h:outputText value="Empleado:"/>
                                <h:outputText id="empl" value="#{solicitudBean.asignado.idEmpleado.toString()}"/>
                            </h:panelGrid>
                            <h:commandLink class="button" value="Asignar Empĺeado" action="#{solicitudBean.actualizarAsignado()}">                               
                            </h:commandLink>
                        </h:form>
                        <ezcomp:ajaxGif/>
                    </div>

                </div>
                <div class="grid-5">&nbsp;</div>

                <div class="grid-100">&nbsp;</div>
                <div class="clear"/>
            </div>

            <div id="pie" class="grid-99">&nbsp;<br/>&nbsp;<br/></div>
        </div>
        <ezcomp:ajaxScript/>
    </h:body>
</html>